### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by trylee** [TinyQ/TQMultistageTableView#11]
1、点击倒数第二个header，展开二级cell
2、然后再点击最后一个header，展开二级cell
3、再点击最后一个header，关闭二级cell，这时候整个Tableview会往下发生很大偏移

**Comment by wtuyp** [comment]
作者没空更新这个库了。参考下这个，不知道有没有更好的办法？
https://github.com/TinyQ/TQMultistageTableView/pull/9/commits/dc01cfe8825cf6fc0eda94ec3422c7f396a978cd

**Comment by TinyQ** [comment]
fix in https://github.com/TinyQ/TQMultistageTableView/pull/9
