### ISSUE TITLE
iOS11下二级展开会出现界面混乱

### ISSUE THREAD

**Issue by tianguanghui** [TinyQ/TQMultistageTableView#6]
![image](https://user-images.githubusercontent.com/1832802/31324593-e134021a-ac79-11e7-97f7-3864695ecadc.png)
如上图，红框部分本应该是最后一个Header的展开的TableViewCell，现在在iOS11下界面显示乱了。

**Comment by tianguanghui** [comment]
iOS11下需要重新初始化一些高度
_tableView.estimatedRowHeight = 0;
_tableView.estimatedSectionFooterHeight = 0;
_tableView.estimatedSectionHeaderHeight = 0;

**Comment by TinyQ** [comment]
#7
